version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      next-eslint:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
      clerk:
        patterns:
          - "@clerk/*"
          - "clerk"
      supabase:
        patterns:
          - "@supabase/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
